[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "Speeedy"
version = "0.0.1"
description = "Speeedy"
authors = [{ name = "Denis Minka", email = "minka.denis@gmail.com" }]
dependencies = []
